// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dut.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dut::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dut::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<5> dut::ap_ST_fsm_state1 = "1";
const sc_lv<5> dut::ap_ST_fsm_state2 = "10";
const sc_lv<5> dut::ap_ST_fsm_state3 = "100";
const sc_lv<5> dut::ap_ST_fsm_state4 = "1000";
const sc_lv<5> dut::ap_ST_fsm_state5 = "10000";
const sc_lv<32> dut::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> dut::ap_const_lv32_1 = "1";
const sc_lv<1> dut::ap_const_lv1_0 = "0";
const sc_lv<32> dut::ap_const_lv32_4 = "100";
const sc_lv<32> dut::ap_const_lv32_3 = "11";
const sc_lv<8> dut::ap_const_lv8_0 = "00000000";
const sc_lv<32> dut::ap_const_lv32_2 = "10";
const sc_lv<1> dut::ap_const_lv1_1 = "1";
const sc_lv<8> dut::ap_const_lv8_80 = "10000000";
const sc_lv<8> dut::ap_const_lv8_1 = "1";
const bool dut::ap_const_boolean_1 = true;

dut::dut(sc_module_name name) : sc_module(name), mVcdFile(0) {
    input1_U = new softmax_128_s_eulbkb("input1_U");
    input1_U->clk(ap_clk);
    input1_U->reset(ap_rst);
    input1_U->address0(input1_address0);
    input1_U->ce0(input1_ce0);
    input1_U->we0(input1_we0);
    input1_U->d0(strm_in_a_V_dout);
    input1_U->q0(input1_q0);
    output_U = new softmax_128_s_eulbkb("output_U");
    output_U->clk(ap_clk);
    output_U->reset(ap_rst);
    output_U->address0(output_address0);
    output_U->ce0(output_ce0);
    output_U->we0(output_we0);
    output_U->d0(grp_softmax_128_s_fu_111_probability_distribu_d0);
    output_U->q0(output_q0);
    grp_softmax_128_s_fu_111 = new softmax_128_s("grp_softmax_128_s_fu_111");
    grp_softmax_128_s_fu_111->ap_clk(ap_clk);
    grp_softmax_128_s_fu_111->ap_rst(ap_rst);
    grp_softmax_128_s_fu_111->ap_start(grp_softmax_128_s_fu_111_ap_start);
    grp_softmax_128_s_fu_111->ap_done(grp_softmax_128_s_fu_111_ap_done);
    grp_softmax_128_s_fu_111->ap_idle(grp_softmax_128_s_fu_111_ap_idle);
    grp_softmax_128_s_fu_111->ap_ready(grp_softmax_128_s_fu_111_ap_ready);
    grp_softmax_128_s_fu_111->output_layer_address0(grp_softmax_128_s_fu_111_output_layer_address0);
    grp_softmax_128_s_fu_111->output_layer_ce0(grp_softmax_128_s_fu_111_output_layer_ce0);
    grp_softmax_128_s_fu_111->output_layer_q0(input1_q0);
    grp_softmax_128_s_fu_111->probability_distribu_address0(grp_softmax_128_s_fu_111_probability_distribu_address0);
    grp_softmax_128_s_fu_111->probability_distribu_ce0(grp_softmax_128_s_fu_111_probability_distribu_ce0);
    grp_softmax_128_s_fu_111->probability_distribu_we0(grp_softmax_128_s_fu_111_probability_distribu_we0);
    grp_softmax_128_s_fu_111->probability_distribu_d0(grp_softmax_128_s_fu_111_probability_distribu_d0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state2);
    sensitive << ( strm_in_a_V_empty_n );
    sensitive << ( icmp_ln14_fu_117_p2 );

    SC_METHOD(thread_ap_block_state2_ignore_call0);
    sensitive << ( strm_in_a_V_empty_n );
    sensitive << ( icmp_ln14_fu_117_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln23_fu_134_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln23_fu_134_p2 );

    SC_METHOD(thread_grp_softmax_128_s_fu_111_ap_start);
    sensitive << ( grp_softmax_128_s_fu_111_ap_start_reg );

    SC_METHOD(thread_i_1_fu_140_p2);
    sensitive << ( i1_0_reg_100 );

    SC_METHOD(thread_i_fu_123_p2);
    sensitive << ( i_0_reg_89 );

    SC_METHOD(thread_icmp_ln14_fu_117_p2);
    sensitive << ( strm_in_a_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln14_fu_117_p2 );
    sensitive << ( i_0_reg_89 );

    SC_METHOD(thread_icmp_ln23_fu_134_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( i1_0_reg_100 );

    SC_METHOD(thread_input1_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln14_fu_117_p2 );
    sensitive << ( grp_softmax_128_s_fu_111_output_layer_address0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext_ln16_fu_129_p1 );

    SC_METHOD(thread_input1_ce0);
    sensitive << ( strm_in_a_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln14_fu_117_p2 );
    sensitive << ( grp_softmax_128_s_fu_111_output_layer_ce0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_input1_we0);
    sensitive << ( strm_in_a_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln14_fu_117_p2 );

    SC_METHOD(thread_output_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( grp_softmax_128_s_fu_111_probability_distribu_address0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext_ln24_fu_146_p1 );

    SC_METHOD(thread_output_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( grp_softmax_128_s_fu_111_probability_distribu_ce0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_output_we0);
    sensitive << ( grp_softmax_128_s_fu_111_probability_distribu_we0 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_strm_in_a_V_blk_n);
    sensitive << ( strm_in_a_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln14_fu_117_p2 );

    SC_METHOD(thread_strm_in_a_V_read);
    sensitive << ( strm_in_a_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln14_fu_117_p2 );

    SC_METHOD(thread_strm_out_V_blk_n);
    sensitive << ( strm_out_V_full_n );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_strm_out_V_din);
    sensitive << ( strm_out_V_full_n );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( output_q0 );

    SC_METHOD(thread_strm_out_V_write);
    sensitive << ( strm_out_V_full_n );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_zext_ln16_fu_129_p1);
    sensitive << ( i_0_reg_89 );

    SC_METHOD(thread_zext_ln24_fu_146_p1);
    sensitive << ( i1_0_reg_100 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( strm_in_a_V_empty_n );
    sensitive << ( strm_out_V_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln14_fu_117_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln23_fu_134_p2 );
    sensitive << ( grp_softmax_128_s_fu_111_ap_done );
    sensitive << ( ap_CS_fsm_state3 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "00001";
    grp_softmax_128_s_fu_111_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dut_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, strm_in_a_V_dout, "(port)strm_in_a_V_dout");
    sc_trace(mVcdFile, strm_in_a_V_empty_n, "(port)strm_in_a_V_empty_n");
    sc_trace(mVcdFile, strm_in_a_V_read, "(port)strm_in_a_V_read");
    sc_trace(mVcdFile, strm_out_V_din, "(port)strm_out_V_din");
    sc_trace(mVcdFile, strm_out_V_full_n, "(port)strm_out_V_full_n");
    sc_trace(mVcdFile, strm_out_V_write, "(port)strm_out_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, strm_in_a_V_blk_n, "strm_in_a_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln14_fu_117_p2, "icmp_ln14_fu_117_p2");
    sc_trace(mVcdFile, strm_out_V_blk_n, "strm_out_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, i_fu_123_p2, "i_fu_123_p2");
    sc_trace(mVcdFile, ap_block_state2, "ap_block_state2");
    sc_trace(mVcdFile, i_1_fu_140_p2, "i_1_fu_140_p2");
    sc_trace(mVcdFile, i_1_reg_162, "i_1_reg_162");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, icmp_ln23_fu_134_p2, "icmp_ln23_fu_134_p2");
    sc_trace(mVcdFile, input1_address0, "input1_address0");
    sc_trace(mVcdFile, input1_ce0, "input1_ce0");
    sc_trace(mVcdFile, input1_we0, "input1_we0");
    sc_trace(mVcdFile, input1_q0, "input1_q0");
    sc_trace(mVcdFile, output_address0, "output_address0");
    sc_trace(mVcdFile, output_ce0, "output_ce0");
    sc_trace(mVcdFile, output_we0, "output_we0");
    sc_trace(mVcdFile, output_q0, "output_q0");
    sc_trace(mVcdFile, grp_softmax_128_s_fu_111_ap_start, "grp_softmax_128_s_fu_111_ap_start");
    sc_trace(mVcdFile, grp_softmax_128_s_fu_111_ap_done, "grp_softmax_128_s_fu_111_ap_done");
    sc_trace(mVcdFile, grp_softmax_128_s_fu_111_ap_idle, "grp_softmax_128_s_fu_111_ap_idle");
    sc_trace(mVcdFile, grp_softmax_128_s_fu_111_ap_ready, "grp_softmax_128_s_fu_111_ap_ready");
    sc_trace(mVcdFile, grp_softmax_128_s_fu_111_output_layer_address0, "grp_softmax_128_s_fu_111_output_layer_address0");
    sc_trace(mVcdFile, grp_softmax_128_s_fu_111_output_layer_ce0, "grp_softmax_128_s_fu_111_output_layer_ce0");
    sc_trace(mVcdFile, grp_softmax_128_s_fu_111_probability_distribu_address0, "grp_softmax_128_s_fu_111_probability_distribu_address0");
    sc_trace(mVcdFile, grp_softmax_128_s_fu_111_probability_distribu_ce0, "grp_softmax_128_s_fu_111_probability_distribu_ce0");
    sc_trace(mVcdFile, grp_softmax_128_s_fu_111_probability_distribu_we0, "grp_softmax_128_s_fu_111_probability_distribu_we0");
    sc_trace(mVcdFile, grp_softmax_128_s_fu_111_probability_distribu_d0, "grp_softmax_128_s_fu_111_probability_distribu_d0");
    sc_trace(mVcdFile, i_0_reg_89, "i_0_reg_89");
    sc_trace(mVcdFile, i1_0_reg_100, "i1_0_reg_100");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, grp_softmax_128_s_fu_111_ap_start_reg, "grp_softmax_128_s_fu_111_ap_start_reg");
    sc_trace(mVcdFile, ap_block_state2_ignore_call0, "ap_block_state2_ignore_call0");
    sc_trace(mVcdFile, zext_ln16_fu_129_p1, "zext_ln16_fu_129_p1");
    sc_trace(mVcdFile, zext_ln24_fu_146_p1, "zext_ln24_fu_146_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("dut.hdltvin.dat");
    mHdltvoutHandle.open("dut.hdltvout.dat");
}

dut::~dut() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete input1_U;
    delete output_U;
    delete grp_softmax_128_s_fu_111;
}

void dut::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_softmax_128_s_fu_111_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
             !(esl_seteq<1,1,1>(icmp_ln14_fu_117_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, strm_in_a_V_empty_n.read())) && 
             esl_seteq<1,1,1>(icmp_ln14_fu_117_p2.read(), ap_const_lv1_1))) {
            grp_softmax_128_s_fu_111_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_softmax_128_s_fu_111_ap_ready.read())) {
            grp_softmax_128_s_fu_111_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(strm_out_V_full_n.read(), ap_const_logic_1))) {
        i1_0_reg_100 = i_1_reg_162.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(grp_softmax_128_s_fu_111_ap_done.read(), ap_const_logic_1))) {
        i1_0_reg_100 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln14_fu_117_p2.read(), ap_const_lv1_0) && 
         !(esl_seteq<1,1,1>(icmp_ln14_fu_117_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, strm_in_a_V_empty_n.read())))) {
        i_0_reg_89 = i_fu_123_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_89 = ap_const_lv8_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        i_1_reg_162 = i_1_fu_140_p2.read();
    }
}

void dut::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void dut::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void dut::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void dut::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void dut::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void dut::thread_ap_block_state2() {
    ap_block_state2 = (esl_seteq<1,1,1>(icmp_ln14_fu_117_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, strm_in_a_V_empty_n.read()));
}

void dut::thread_ap_block_state2_ignore_call0() {
    ap_block_state2_ignore_call0 = (esl_seteq<1,1,1>(icmp_ln14_fu_117_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, strm_in_a_V_empty_n.read()));
}

void dut::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln23_fu_134_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dut::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dut::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln23_fu_134_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dut::thread_grp_softmax_128_s_fu_111_ap_start() {
    grp_softmax_128_s_fu_111_ap_start = grp_softmax_128_s_fu_111_ap_start_reg.read();
}

void dut::thread_i_1_fu_140_p2() {
    i_1_fu_140_p2 = (!i1_0_reg_100.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(i1_0_reg_100.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void dut::thread_i_fu_123_p2() {
    i_fu_123_p2 = (!i_0_reg_89.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(i_0_reg_89.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void dut::thread_icmp_ln14_fu_117_p2() {
    icmp_ln14_fu_117_p2 = (!i_0_reg_89.read().is_01() || !ap_const_lv8_80.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_89.read() == ap_const_lv8_80);
}

void dut::thread_icmp_ln23_fu_134_p2() {
    icmp_ln23_fu_134_p2 = (!i1_0_reg_100.read().is_01() || !ap_const_lv8_80.is_01())? sc_lv<1>(): sc_lv<1>(i1_0_reg_100.read() == ap_const_lv8_80);
}

void dut::thread_input1_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln14_fu_117_p2.read(), ap_const_lv1_0))) {
        input1_address0 =  (sc_lv<7>) (zext_ln16_fu_129_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        input1_address0 = grp_softmax_128_s_fu_111_output_layer_address0.read();
    } else {
        input1_address0 = "XXXXXXX";
    }
}

void dut::thread_input1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln14_fu_117_p2.read(), ap_const_lv1_0) && 
         !(esl_seteq<1,1,1>(icmp_ln14_fu_117_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, strm_in_a_V_empty_n.read())))) {
        input1_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        input1_ce0 = grp_softmax_128_s_fu_111_output_layer_ce0.read();
    } else {
        input1_ce0 = ap_const_logic_0;
    }
}

void dut::thread_input1_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln14_fu_117_p2.read(), ap_const_lv1_0) && 
         !(esl_seteq<1,1,1>(icmp_ln14_fu_117_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, strm_in_a_V_empty_n.read())))) {
        input1_we0 = ap_const_logic_1;
    } else {
        input1_we0 = ap_const_logic_0;
    }
}

void dut::thread_output_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        output_address0 =  (sc_lv<7>) (zext_ln24_fu_146_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        output_address0 = grp_softmax_128_s_fu_111_probability_distribu_address0.read();
    } else {
        output_address0 = "XXXXXXX";
    }
}

void dut::thread_output_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        output_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        output_ce0 = grp_softmax_128_s_fu_111_probability_distribu_ce0.read();
    } else {
        output_ce0 = ap_const_logic_0;
    }
}

void dut::thread_output_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        output_we0 = grp_softmax_128_s_fu_111_probability_distribu_we0.read();
    } else {
        output_we0 = ap_const_logic_0;
    }
}

void dut::thread_strm_in_a_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln14_fu_117_p2.read(), ap_const_lv1_0))) {
        strm_in_a_V_blk_n = strm_in_a_V_empty_n.read();
    } else {
        strm_in_a_V_blk_n = ap_const_logic_1;
    }
}

void dut::thread_strm_in_a_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln14_fu_117_p2.read(), ap_const_lv1_0) && 
         !(esl_seteq<1,1,1>(icmp_ln14_fu_117_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, strm_in_a_V_empty_n.read())))) {
        strm_in_a_V_read = ap_const_logic_1;
    } else {
        strm_in_a_V_read = ap_const_logic_0;
    }
}

void dut::thread_strm_out_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        strm_out_V_blk_n = strm_out_V_full_n.read();
    } else {
        strm_out_V_blk_n = ap_const_logic_1;
    }
}

void dut::thread_strm_out_V_din() {
    strm_out_V_din = output_q0.read();
}

void dut::thread_strm_out_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(strm_out_V_full_n.read(), ap_const_logic_1))) {
        strm_out_V_write = ap_const_logic_1;
    } else {
        strm_out_V_write = ap_const_logic_0;
    }
}

void dut::thread_zext_ln16_fu_129_p1() {
    zext_ln16_fu_129_p1 = esl_zext<64,8>(i_0_reg_89.read());
}

void dut::thread_zext_ln24_fu_146_p1() {
    zext_ln24_fu_146_p1 = esl_zext<64,8>(i1_0_reg_100.read());
}

void dut::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln14_fu_117_p2.read(), ap_const_lv1_0) && !(esl_seteq<1,1,1>(icmp_ln14_fu_117_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, strm_in_a_V_empty_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && !(esl_seteq<1,1,1>(icmp_ln14_fu_117_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, strm_in_a_V_empty_n.read())) && esl_seteq<1,1,1>(icmp_ln14_fu_117_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(grp_softmax_128_s_fu_111_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln23_fu_134_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(strm_out_V_full_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<5>) ("XXXXX");
            break;
    }
}

void dut::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"strm_in_a_V_dout\" :  \"" << strm_in_a_V_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"strm_in_a_V_empty_n\" :  \"" << strm_in_a_V_empty_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"strm_in_a_V_read\" :  \"" << strm_in_a_V_read.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"strm_out_V_din\" :  \"" << strm_out_V_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"strm_out_V_full_n\" :  \"" << strm_out_V_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"strm_out_V_write\" :  \"" << strm_out_V_write.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

