// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "softmax_128_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic softmax_128_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic softmax_128_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<69> softmax_128_s::ap_ST_fsm_state1 = "1";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state2 = "10";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state3 = "100";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state4 = "1000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state5 = "10000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state6 = "100000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state7 = "1000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state8 = "10000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state9 = "100000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state10 = "1000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state11 = "10000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state12 = "100000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state34 = "1000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state35 = "10000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state36 = "100000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state37 = "1000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state38 = "10000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state39 = "100000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state40 = "1000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state41 = "10000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state42 = "100000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state43 = "1000000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state44 = "10000000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state45 = "100000000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state46 = "1000000000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state47 = "10000000000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state48 = "100000000000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state49 = "1000000000000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state50 = "10000000000000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state51 = "100000000000000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state52 = "1000000000000000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state53 = "10000000000000000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state54 = "100000000000000000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state55 = "1000000000000000000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state56 = "10000000000000000000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state57 = "100000000000000000000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state58 = "1000000000000000000000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state59 = "10000000000000000000000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state60 = "100000000000000000000000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state61 = "1000000000000000000000000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state62 = "10000000000000000000000000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state63 = "100000000000000000000000000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state64 = "1000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state65 = "10000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state66 = "100000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state67 = "1000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state68 = "10000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<69> softmax_128_s::ap_ST_fsm_state69 = "100000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> softmax_128_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> softmax_128_s::ap_const_lv32_19 = "11001";
const sc_lv<32> softmax_128_s::ap_const_lv32_43 = "1000011";
const sc_lv<32> softmax_128_s::ap_const_lv32_1B = "11011";
const sc_lv<32> softmax_128_s::ap_const_lv32_22 = "100010";
const sc_lv<32> softmax_128_s::ap_const_lv32_1 = "1";
const sc_lv<1> softmax_128_s::ap_const_lv1_0 = "0";
const sc_lv<32> softmax_128_s::ap_const_lv32_2 = "10";
const sc_lv<32> softmax_128_s::ap_const_lv32_3 = "11";
const sc_lv<32> softmax_128_s::ap_const_lv32_4 = "100";
const sc_lv<1> softmax_128_s::ap_const_lv1_1 = "1";
const sc_lv<32> softmax_128_s::ap_const_lv32_9 = "1001";
const sc_lv<32> softmax_128_s::ap_const_lv32_21 = "100001";
const sc_lv<32> softmax_128_s::ap_const_lv32_27 = "100111";
const sc_lv<32> softmax_128_s::ap_const_lv32_29 = "101001";
const sc_lv<32> softmax_128_s::ap_const_lv32_2C = "101100";
const sc_lv<32> softmax_128_s::ap_const_lv32_31 = "110001";
const sc_lv<32> softmax_128_s::ap_const_lv32_32 = "110010";
const sc_lv<32> softmax_128_s::ap_const_lv32_33 = "110011";
const sc_lv<8> softmax_128_s::ap_const_lv8_0 = "00000000";
const sc_lv<32> softmax_128_s::ap_const_lv32_3F800000 = "111111100000000000000000000000";
const sc_lv<7> softmax_128_s::ap_const_lv7_2 = "10";
const sc_lv<64> softmax_128_s::ap_const_lv64_3FF0000000000000 = "11111111110000000000000000000000000000000000000000000000000000";
const sc_lv<32> softmax_128_s::ap_const_lv32_44 = "1000100";
const sc_lv<32> softmax_128_s::ap_const_lv32_2D = "101101";
const sc_lv<32> softmax_128_s::ap_const_lv32_402DF854 = "1000000001011011111100001010100";
const sc_lv<32> softmax_128_s::ap_const_lv32_A = "1010";
const sc_lv<32> softmax_128_s::ap_const_lv32_34 = "110100";
const sc_lv<32> softmax_128_s::ap_const_lv32_28 = "101000";
const sc_lv<32> softmax_128_s::ap_const_lv32_1A = "11010";
const sc_lv<32> softmax_128_s::ap_const_lv32_23 = "100011";
const sc_lv<32> softmax_128_s::ap_const_lv32_1C = "11100";
const sc_lv<8> softmax_128_s::ap_const_lv8_80 = "10000000";
const sc_lv<8> softmax_128_s::ap_const_lv8_1 = "1";
const sc_lv<7> softmax_128_s::ap_const_lv7_66 = "1100110";
const sc_lv<7> softmax_128_s::ap_const_lv7_1 = "1";
const bool softmax_128_s::ap_const_boolean_1 = true;

softmax_128_s::softmax_128_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    euler_sums_U = new softmax_128_s_eulbkb("euler_sums_U");
    euler_sums_U->clk(ap_clk);
    euler_sums_U->reset(ap_rst);
    euler_sums_U->address0(euler_sums_address0);
    euler_sums_U->ce0(euler_sums_ce0);
    euler_sums_U->we0(euler_sums_we0);
    euler_sums_U->d0(tmp_1_reg_341);
    euler_sums_U->q0(euler_sums_q0);
    dut_fadd_32ns_32ncud_U1 = new dut_fadd_32ns_32ncud<1,5,32,32,32>("dut_fadd_32ns_32ncud_U1");
    dut_fadd_32ns_32ncud_U1->clk(ap_clk);
    dut_fadd_32ns_32ncud_U1->reset(ap_rst);
    dut_fadd_32ns_32ncud_U1->din0(euler_layer_sum_0_reg_95);
    dut_fadd_32ns_32ncud_U1->din1(tmp_1_reg_341);
    dut_fadd_32ns_32ncud_U1->ce(ap_var_for_const0);
    dut_fadd_32ns_32ncud_U1->dout(grp_fu_166_p2);
    dut_fmul_32ns_32ndEe_U2 = new dut_fmul_32ns_32ndEe<1,4,32,32,32>("dut_fmul_32ns_32ndEe_U2");
    dut_fmul_32ns_32ndEe_U2->clk(ap_clk);
    dut_fmul_32ns_32ndEe_U2->reset(ap_rst);
    dut_fmul_32ns_32ndEe_U2->din0(empty_4_reg_107);
    dut_fmul_32ns_32ndEe_U2->din1(ap_var_for_const1);
    dut_fmul_32ns_32ndEe_U2->ce(ap_var_for_const0);
    dut_fmul_32ns_32ndEe_U2->dout(grp_fu_171_p2);
    dut_fdiv_32ns_32neOg_U3 = new dut_fdiv_32ns_32neOg<1,16,32,32,32>("dut_fdiv_32ns_32neOg_U3");
    dut_fdiv_32ns_32neOg_U3->clk(ap_clk);
    dut_fdiv_32ns_32neOg_U3->reset(ap_rst);
    dut_fdiv_32ns_32neOg_U3->din0(grp_fu_177_p0);
    dut_fdiv_32ns_32neOg_U3->din1(grp_fu_177_p1);
    dut_fdiv_32ns_32neOg_U3->ce(ap_var_for_const0);
    dut_fdiv_32ns_32neOg_U3->dout(grp_fu_177_p2);
    dut_sitofp_32ns_3fYi_U4 = new dut_sitofp_32ns_3fYi<1,6,32,32>("dut_sitofp_32ns_3fYi_U4");
    dut_sitofp_32ns_3fYi_U4->clk(ap_clk);
    dut_sitofp_32ns_3fYi_U4->reset(ap_rst);
    dut_sitofp_32ns_3fYi_U4->din0(k_0_reg_143);
    dut_sitofp_32ns_3fYi_U4->ce(ap_var_for_const0);
    dut_sitofp_32ns_3fYi_U4->dout(grp_fu_182_p1);
    dut_fptrunc_64ns_g8j_U5 = new dut_fptrunc_64ns_g8j<1,2,64,32>("dut_fptrunc_64ns_g8j_U5");
    dut_fptrunc_64ns_g8j_U5->clk(ap_clk);
    dut_fptrunc_64ns_g8j_U5->reset(ap_rst);
    dut_fptrunc_64ns_g8j_U5->din0(tmp_4_reg_331);
    dut_fptrunc_64ns_g8j_U5->ce(ap_var_for_const0);
    dut_fptrunc_64ns_g8j_U5->dout(grp_fu_186_p1);
    dut_fpext_32ns_64hbi_U6 = new dut_fpext_32ns_64hbi<1,2,32,64>("dut_fpext_32ns_64hbi_U6");
    dut_fpext_32ns_64hbi_U6->clk(ap_clk);
    dut_fpext_32ns_64hbi_U6->reset(ap_rst);
    dut_fpext_32ns_64hbi_U6->din0(grp_fu_189_p0);
    dut_fpext_32ns_64hbi_U6->ce(ap_var_for_const0);
    dut_fpext_32ns_64hbi_U6->dout(grp_fu_189_p1);
    dut_dadd_64ns_64nibs_U7 = new dut_dadd_64ns_64nibs<1,5,64,64,64>("dut_dadd_64ns_64nibs_U7");
    dut_dadd_64ns_64nibs_U7->clk(ap_clk);
    dut_dadd_64ns_64nibs_U7->reset(ap_rst);
    dut_dadd_64ns_64nibs_U7->din0(reg_209);
    dut_dadd_64ns_64nibs_U7->din1(term_0_reg_131);
    dut_dadd_64ns_64nibs_U7->ce(ap_var_for_const0);
    dut_dadd_64ns_64nibs_U7->dout(grp_fu_193_p2);
    dut_dmul_64ns_64njbC_U8 = new dut_dmul_64ns_64njbC<1,6,64,64,64>("dut_dmul_64ns_64njbC_U8");
    dut_dmul_64ns_64njbC_U8->clk(ap_clk);
    dut_dmul_64ns_64njbC_U8->reset(ap_rst);
    dut_dmul_64ns_64njbC_U8->din0(term_0_reg_131);
    dut_dmul_64ns_64njbC_U8->din1(reg_209);
    dut_dmul_64ns_64njbC_U8->ce(ap_var_for_const0);
    dut_dmul_64ns_64njbC_U8->dout(grp_fu_198_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln19_fu_254_p2);
    sensitive << ( indvars_iv_reg_119 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state26);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state27);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state28);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state29);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state34);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state35);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state36);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state40);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state41);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state42);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state45);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state46);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state50);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state51);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state52);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state53);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state68);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state69);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state51 );
    sensitive << ( icmp_ln32_fu_260_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state51 );
    sensitive << ( icmp_ln32_fu_260_p2 );

    SC_METHOD(thread_euler_sums_address0);
    sensitive << ( euler_sums_addr_reg_285 );
    sensitive << ( ap_CS_fsm_state51 );
    sensitive << ( zext_ln33_fu_272_p1 );
    sensitive << ( ap_CS_fsm_state46 );

    SC_METHOD(thread_euler_sums_ce0);
    sensitive << ( ap_CS_fsm_state51 );
    sensitive << ( ap_CS_fsm_state46 );

    SC_METHOD(thread_euler_sums_we0);
    sensitive << ( ap_CS_fsm_state46 );

    SC_METHOD(thread_grp_fu_177_p0);
    sensitive << ( output_layer_load_reg_295 );
    sensitive << ( euler_sums_load_reg_370 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state53 );

    SC_METHOD(thread_grp_fu_177_p1);
    sensitive << ( tmp_6_reg_321 );
    sensitive << ( euler_layer_sum_0_reg_95 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state53 );

    SC_METHOD(thread_grp_fu_189_p0);
    sensitive << ( reg_203 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( empty_4_reg_107 );
    sensitive << ( ap_CS_fsm_state27 );

    SC_METHOD(thread_i_fu_221_p2);
    sensitive << ( i_0_reg_84 );

    SC_METHOD(thread_icmp_ln16_fu_215_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_84 );

    SC_METHOD(thread_icmp_ln19_fu_237_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( indvars_iv_reg_119 );

    SC_METHOD(thread_icmp_ln21_fu_243_p2);
    sensitive << ( zext_ln19_reg_300 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( k_0_reg_143 );

    SC_METHOD(thread_icmp_ln32_fu_260_p2);
    sensitive << ( ap_CS_fsm_state51 );
    sensitive << ( j1_0_reg_155 );

    SC_METHOD(thread_j_fu_266_p2);
    sensitive << ( j1_0_reg_155 );

    SC_METHOD(thread_k_fu_248_p2);
    sensitive << ( k_0_reg_143 );

    SC_METHOD(thread_output_layer_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln18_fu_227_p1 );

    SC_METHOD(thread_output_layer_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_probability_distribu_address0);
    sensitive << ( zext_ln33_reg_360 );
    sensitive << ( ap_CS_fsm_state69 );

    SC_METHOD(thread_probability_distribu_ce0);
    sensitive << ( ap_CS_fsm_state69 );

    SC_METHOD(thread_probability_distribu_d0);
    sensitive << ( reg_203 );
    sensitive << ( ap_CS_fsm_state69 );

    SC_METHOD(thread_probability_distribu_we0);
    sensitive << ( ap_CS_fsm_state69 );

    SC_METHOD(thread_zext_ln18_fu_227_p1);
    sensitive << ( i_0_reg_84 );

    SC_METHOD(thread_zext_ln19_fu_233_p1);
    sensitive << ( indvars_iv_reg_119 );

    SC_METHOD(thread_zext_ln33_fu_272_p1);
    sensitive << ( j1_0_reg_155 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln16_fu_215_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln21_fu_243_p2 );
    sensitive << ( ap_CS_fsm_state51 );
    sensitive << ( icmp_ln32_fu_260_p2 );
    sensitive << ( icmp_ln19_fu_237_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    ap_CS_fsm = "000000000000000000000000000000000000000000000000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "softmax_128_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, output_layer_address0, "(port)output_layer_address0");
    sc_trace(mVcdFile, output_layer_ce0, "(port)output_layer_ce0");
    sc_trace(mVcdFile, output_layer_q0, "(port)output_layer_q0");
    sc_trace(mVcdFile, probability_distribu_address0, "(port)probability_distribu_address0");
    sc_trace(mVcdFile, probability_distribu_ce0, "(port)probability_distribu_ce0");
    sc_trace(mVcdFile, probability_distribu_we0, "(port)probability_distribu_we0");
    sc_trace(mVcdFile, probability_distribu_d0, "(port)probability_distribu_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, grp_fu_177_p2, "grp_fu_177_p2");
    sc_trace(mVcdFile, reg_203, "reg_203");
    sc_trace(mVcdFile, ap_CS_fsm_state26, "ap_CS_fsm_state26");
    sc_trace(mVcdFile, ap_CS_fsm_state68, "ap_CS_fsm_state68");
    sc_trace(mVcdFile, grp_fu_189_p1, "grp_fu_189_p1");
    sc_trace(mVcdFile, reg_209, "reg_209");
    sc_trace(mVcdFile, ap_CS_fsm_state28, "ap_CS_fsm_state28");
    sc_trace(mVcdFile, ap_CS_fsm_state35, "ap_CS_fsm_state35");
    sc_trace(mVcdFile, i_fu_221_p2, "i_fu_221_p2");
    sc_trace(mVcdFile, i_reg_280, "i_reg_280");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, euler_sums_addr_reg_285, "euler_sums_addr_reg_285");
    sc_trace(mVcdFile, icmp_ln16_fu_215_p2, "icmp_ln16_fu_215_p2");
    sc_trace(mVcdFile, output_layer_load_reg_295, "output_layer_load_reg_295");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, zext_ln19_fu_233_p1, "zext_ln19_fu_233_p1");
    sc_trace(mVcdFile, zext_ln19_reg_300, "zext_ln19_reg_300");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, k_fu_248_p2, "k_fu_248_p2");
    sc_trace(mVcdFile, k_reg_311, "k_reg_311");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, icmp_ln21_fu_243_p2, "icmp_ln21_fu_243_p2");
    sc_trace(mVcdFile, add_ln19_fu_254_p2, "add_ln19_fu_254_p2");
    sc_trace(mVcdFile, add_ln19_reg_316, "add_ln19_reg_316");
    sc_trace(mVcdFile, grp_fu_182_p1, "grp_fu_182_p1");
    sc_trace(mVcdFile, tmp_6_reg_321, "tmp_6_reg_321");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, grp_fu_198_p2, "grp_fu_198_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state34, "ap_CS_fsm_state34");
    sc_trace(mVcdFile, grp_fu_193_p2, "grp_fu_193_p2");
    sc_trace(mVcdFile, tmp_4_reg_331, "tmp_4_reg_331");
    sc_trace(mVcdFile, ap_CS_fsm_state40, "ap_CS_fsm_state40");
    sc_trace(mVcdFile, grp_fu_186_p1, "grp_fu_186_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state42, "ap_CS_fsm_state42");
    sc_trace(mVcdFile, grp_fu_171_p2, "grp_fu_171_p2");
    sc_trace(mVcdFile, tmp_1_reg_341, "tmp_1_reg_341");
    sc_trace(mVcdFile, ap_CS_fsm_state45, "ap_CS_fsm_state45");
    sc_trace(mVcdFile, grp_fu_166_p2, "grp_fu_166_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state50, "ap_CS_fsm_state50");
    sc_trace(mVcdFile, j_fu_266_p2, "j_fu_266_p2");
    sc_trace(mVcdFile, j_reg_355, "j_reg_355");
    sc_trace(mVcdFile, ap_CS_fsm_state51, "ap_CS_fsm_state51");
    sc_trace(mVcdFile, zext_ln33_fu_272_p1, "zext_ln33_fu_272_p1");
    sc_trace(mVcdFile, zext_ln33_reg_360, "zext_ln33_reg_360");
    sc_trace(mVcdFile, icmp_ln32_fu_260_p2, "icmp_ln32_fu_260_p2");
    sc_trace(mVcdFile, euler_sums_q0, "euler_sums_q0");
    sc_trace(mVcdFile, euler_sums_load_reg_370, "euler_sums_load_reg_370");
    sc_trace(mVcdFile, ap_CS_fsm_state52, "ap_CS_fsm_state52");
    sc_trace(mVcdFile, euler_sums_address0, "euler_sums_address0");
    sc_trace(mVcdFile, euler_sums_ce0, "euler_sums_ce0");
    sc_trace(mVcdFile, euler_sums_we0, "euler_sums_we0");
    sc_trace(mVcdFile, i_0_reg_84, "i_0_reg_84");
    sc_trace(mVcdFile, euler_layer_sum_0_reg_95, "euler_layer_sum_0_reg_95");
    sc_trace(mVcdFile, empty_4_reg_107, "empty_4_reg_107");
    sc_trace(mVcdFile, indvars_iv_reg_119, "indvars_iv_reg_119");
    sc_trace(mVcdFile, term_0_reg_131, "term_0_reg_131");
    sc_trace(mVcdFile, icmp_ln19_fu_237_p2, "icmp_ln19_fu_237_p2");
    sc_trace(mVcdFile, k_0_reg_143, "k_0_reg_143");
    sc_trace(mVcdFile, j1_0_reg_155, "j1_0_reg_155");
    sc_trace(mVcdFile, ap_CS_fsm_state69, "ap_CS_fsm_state69");
    sc_trace(mVcdFile, zext_ln18_fu_227_p1, "zext_ln18_fu_227_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state46, "ap_CS_fsm_state46");
    sc_trace(mVcdFile, grp_fu_177_p0, "grp_fu_177_p0");
    sc_trace(mVcdFile, grp_fu_177_p1, "grp_fu_177_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_CS_fsm_state53, "ap_CS_fsm_state53");
    sc_trace(mVcdFile, ap_CS_fsm_state41, "ap_CS_fsm_state41");
    sc_trace(mVcdFile, grp_fu_189_p0, "grp_fu_189_p0");
    sc_trace(mVcdFile, ap_CS_fsm_state27, "ap_CS_fsm_state27");
    sc_trace(mVcdFile, ap_CS_fsm_state36, "ap_CS_fsm_state36");
    sc_trace(mVcdFile, ap_CS_fsm_state29, "ap_CS_fsm_state29");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

softmax_128_s::~softmax_128_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete euler_sums_U;
    delete dut_fadd_32ns_32ncud_U1;
    delete dut_fmul_32ns_32ndEe_U2;
    delete dut_fdiv_32ns_32neOg_U3;
    delete dut_sitofp_32ns_3fYi_U4;
    delete dut_fptrunc_64ns_g8j_U5;
    delete dut_fpext_32ns_64hbi_U6;
    delete dut_dadd_64ns_64nibs_U7;
    delete dut_dmul_64ns_64njbC_U8;
}

void softmax_128_s::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void softmax_128_s::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv32_402DF854;
}

void softmax_128_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        empty_4_reg_107 = ap_const_lv32_3F800000;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read())) {
        empty_4_reg_107 = grp_fu_186_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state50.read())) {
        euler_layer_sum_0_reg_95 = grp_fu_166_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        euler_layer_sum_0_reg_95 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state50.read())) {
        i_0_reg_84 = i_reg_280.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_84 = ap_const_lv8_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        indvars_iv_reg_119 = ap_const_lv7_2;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read())) {
        indvars_iv_reg_119 = add_ln19_reg_316.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln16_fu_215_p2.read(), ap_const_lv1_1))) {
        j1_0_reg_155 = ap_const_lv8_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state69.read())) {
        j1_0_reg_155 = j_reg_355.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln19_fu_237_p2.read()))) {
        k_0_reg_143 = ap_const_lv32_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state34.read())) {
        k_0_reg_143 = k_reg_311.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln19_fu_237_p2.read()))) {
        term_0_reg_131 = ap_const_lv64_3FF0000000000000;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state34.read())) {
        term_0_reg_131 = grp_fu_198_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln21_fu_243_p2.read(), ap_const_lv1_1))) {
        add_ln19_reg_316 = add_ln19_fu_254_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln16_fu_215_p2.read(), ap_const_lv1_0))) {
        euler_sums_addr_reg_285 =  (sc_lv<7>) (zext_ln18_fu_227_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state52.read())) {
        euler_sums_load_reg_370 = euler_sums_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_280 = i_fu_221_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state51.read())) {
        j_reg_355 = j_fu_266_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln21_fu_243_p2.read()))) {
        k_reg_311 = k_fu_248_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        output_layer_load_reg_295 = output_layer_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state68.read()))) {
        reg_203 = grp_fu_177_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state35.read()))) {
        reg_209 = grp_fu_189_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state45.read())) {
        tmp_1_reg_341 = grp_fu_171_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state40.read())) {
        tmp_4_reg_331 = grp_fu_193_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        tmp_6_reg_321 = grp_fu_182_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        zext_ln19_reg_300 = zext_ln19_fu_233_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state51.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln32_fu_260_p2.read()))) {
        zext_ln33_reg_360 = zext_ln33_fu_272_p1.read();
    }
}

void softmax_128_s::thread_add_ln19_fu_254_p2() {
    add_ln19_fu_254_p2 = (!indvars_iv_reg_119.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(indvars_iv_reg_119.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void softmax_128_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void softmax_128_s::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void softmax_128_s::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void softmax_128_s::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void softmax_128_s::thread_ap_CS_fsm_state26() {
    ap_CS_fsm_state26 = ap_CS_fsm.read()[25];
}

void softmax_128_s::thread_ap_CS_fsm_state27() {
    ap_CS_fsm_state27 = ap_CS_fsm.read()[26];
}

void softmax_128_s::thread_ap_CS_fsm_state28() {
    ap_CS_fsm_state28 = ap_CS_fsm.read()[27];
}

void softmax_128_s::thread_ap_CS_fsm_state29() {
    ap_CS_fsm_state29 = ap_CS_fsm.read()[28];
}

void softmax_128_s::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void softmax_128_s::thread_ap_CS_fsm_state34() {
    ap_CS_fsm_state34 = ap_CS_fsm.read()[33];
}

void softmax_128_s::thread_ap_CS_fsm_state35() {
    ap_CS_fsm_state35 = ap_CS_fsm.read()[34];
}

void softmax_128_s::thread_ap_CS_fsm_state36() {
    ap_CS_fsm_state36 = ap_CS_fsm.read()[35];
}

void softmax_128_s::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void softmax_128_s::thread_ap_CS_fsm_state40() {
    ap_CS_fsm_state40 = ap_CS_fsm.read()[39];
}

void softmax_128_s::thread_ap_CS_fsm_state41() {
    ap_CS_fsm_state41 = ap_CS_fsm.read()[40];
}

void softmax_128_s::thread_ap_CS_fsm_state42() {
    ap_CS_fsm_state42 = ap_CS_fsm.read()[41];
}

void softmax_128_s::thread_ap_CS_fsm_state45() {
    ap_CS_fsm_state45 = ap_CS_fsm.read()[44];
}

void softmax_128_s::thread_ap_CS_fsm_state46() {
    ap_CS_fsm_state46 = ap_CS_fsm.read()[45];
}

void softmax_128_s::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void softmax_128_s::thread_ap_CS_fsm_state50() {
    ap_CS_fsm_state50 = ap_CS_fsm.read()[49];
}

void softmax_128_s::thread_ap_CS_fsm_state51() {
    ap_CS_fsm_state51 = ap_CS_fsm.read()[50];
}

void softmax_128_s::thread_ap_CS_fsm_state52() {
    ap_CS_fsm_state52 = ap_CS_fsm.read()[51];
}

void softmax_128_s::thread_ap_CS_fsm_state53() {
    ap_CS_fsm_state53 = ap_CS_fsm.read()[52];
}

void softmax_128_s::thread_ap_CS_fsm_state68() {
    ap_CS_fsm_state68 = ap_CS_fsm.read()[67];
}

void softmax_128_s::thread_ap_CS_fsm_state69() {
    ap_CS_fsm_state69 = ap_CS_fsm.read()[68];
}

void softmax_128_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state51.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln32_fu_260_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void softmax_128_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void softmax_128_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state51.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln32_fu_260_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void softmax_128_s::thread_euler_sums_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state51.read())) {
        euler_sums_address0 =  (sc_lv<7>) (zext_ln33_fu_272_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state46.read())) {
        euler_sums_address0 = euler_sums_addr_reg_285.read();
    } else {
        euler_sums_address0 = "XXXXXXX";
    }
}

void softmax_128_s::thread_euler_sums_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state51.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state46.read()))) {
        euler_sums_ce0 = ap_const_logic_1;
    } else {
        euler_sums_ce0 = ap_const_logic_0;
    }
}

void softmax_128_s::thread_euler_sums_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state46.read())) {
        euler_sums_we0 = ap_const_logic_1;
    } else {
        euler_sums_we0 = ap_const_logic_0;
    }
}

void softmax_128_s::thread_grp_fu_177_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state53.read())) {
        grp_fu_177_p0 = euler_sums_load_reg_370.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        grp_fu_177_p0 = output_layer_load_reg_295.read();
    } else {
        grp_fu_177_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void softmax_128_s::thread_grp_fu_177_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state53.read())) {
        grp_fu_177_p1 = euler_layer_sum_0_reg_95.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        grp_fu_177_p1 = tmp_6_reg_321.read();
    } else {
        grp_fu_177_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void softmax_128_s::thread_grp_fu_189_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read())) {
        grp_fu_189_p0 = reg_203.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        grp_fu_189_p0 = empty_4_reg_107.read();
    } else {
        grp_fu_189_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void softmax_128_s::thread_i_fu_221_p2() {
    i_fu_221_p2 = (!i_0_reg_84.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(i_0_reg_84.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void softmax_128_s::thread_icmp_ln16_fu_215_p2() {
    icmp_ln16_fu_215_p2 = (!i_0_reg_84.read().is_01() || !ap_const_lv8_80.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_84.read() == ap_const_lv8_80);
}

void softmax_128_s::thread_icmp_ln19_fu_237_p2() {
    icmp_ln19_fu_237_p2 = (!indvars_iv_reg_119.read().is_01() || !ap_const_lv7_66.is_01())? sc_lv<1>(): sc_lv<1>(indvars_iv_reg_119.read() == ap_const_lv7_66);
}

void softmax_128_s::thread_icmp_ln21_fu_243_p2() {
    icmp_ln21_fu_243_p2 = (!k_0_reg_143.read().is_01() || !zext_ln19_reg_300.read().is_01())? sc_lv<1>(): sc_lv<1>(k_0_reg_143.read() == zext_ln19_reg_300.read());
}

void softmax_128_s::thread_icmp_ln32_fu_260_p2() {
    icmp_ln32_fu_260_p2 = (!j1_0_reg_155.read().is_01() || !ap_const_lv8_80.is_01())? sc_lv<1>(): sc_lv<1>(j1_0_reg_155.read() == ap_const_lv8_80);
}

void softmax_128_s::thread_j_fu_266_p2() {
    j_fu_266_p2 = (!j1_0_reg_155.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(j1_0_reg_155.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void softmax_128_s::thread_k_fu_248_p2() {
    k_fu_248_p2 = (!k_0_reg_143.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(k_0_reg_143.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void softmax_128_s::thread_output_layer_address0() {
    output_layer_address0 =  (sc_lv<7>) (zext_ln18_fu_227_p1.read());
}

void softmax_128_s::thread_output_layer_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        output_layer_ce0 = ap_const_logic_1;
    } else {
        output_layer_ce0 = ap_const_logic_0;
    }
}

void softmax_128_s::thread_probability_distribu_address0() {
    probability_distribu_address0 =  (sc_lv<7>) (zext_ln33_reg_360.read());
}

void softmax_128_s::thread_probability_distribu_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state69.read())) {
        probability_distribu_ce0 = ap_const_logic_1;
    } else {
        probability_distribu_ce0 = ap_const_logic_0;
    }
}

void softmax_128_s::thread_probability_distribu_d0() {
    probability_distribu_d0 = reg_203.read();
}

void softmax_128_s::thread_probability_distribu_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state69.read())) {
        probability_distribu_we0 = ap_const_logic_1;
    } else {
        probability_distribu_we0 = ap_const_logic_0;
    }
}

void softmax_128_s::thread_zext_ln18_fu_227_p1() {
    zext_ln18_fu_227_p1 = esl_zext<64,8>(i_0_reg_84.read());
}

void softmax_128_s::thread_zext_ln19_fu_233_p1() {
    zext_ln19_fu_233_p1 = esl_zext<32,7>(indvars_iv_reg_119.read());
}

void softmax_128_s::thread_zext_ln33_fu_272_p1() {
    zext_ln33_fu_272_p1 = esl_zext<64,8>(j1_0_reg_155.read());
}

void softmax_128_s::thread_ap_NS_fsm() {
    if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state1))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_NS_fsm = ap_ST_fsm_state2;
        } else {
            ap_NS_fsm = ap_ST_fsm_state1;
        }
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state2))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln16_fu_215_p2.read(), ap_const_lv1_1))) {
            ap_NS_fsm = ap_ST_fsm_state51;
        } else {
            ap_NS_fsm = ap_ST_fsm_state3;
        }
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state3))
    {
        ap_NS_fsm = ap_ST_fsm_state4;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state4))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln19_fu_237_p2.read()))) {
            ap_NS_fsm = ap_ST_fsm_state5;
        } else {
            ap_NS_fsm = ap_ST_fsm_state43;
        }
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state5))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln21_fu_243_p2.read(), ap_const_lv1_1))) {
            ap_NS_fsm = ap_ST_fsm_state35;
        } else {
            ap_NS_fsm = ap_ST_fsm_state6;
        }
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state6))
    {
        ap_NS_fsm = ap_ST_fsm_state7;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state7))
    {
        ap_NS_fsm = ap_ST_fsm_state8;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state8))
    {
        ap_NS_fsm = ap_ST_fsm_state9;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state9))
    {
        ap_NS_fsm = ap_ST_fsm_state10;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state10))
    {
        ap_NS_fsm = ap_ST_fsm_state11;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state11))
    {
        ap_NS_fsm = ap_ST_fsm_state12;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state12))
    {
        ap_NS_fsm = ap_ST_fsm_state13;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state13))
    {
        ap_NS_fsm = ap_ST_fsm_state14;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state14))
    {
        ap_NS_fsm = ap_ST_fsm_state15;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state15))
    {
        ap_NS_fsm = ap_ST_fsm_state16;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state16))
    {
        ap_NS_fsm = ap_ST_fsm_state17;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state17))
    {
        ap_NS_fsm = ap_ST_fsm_state18;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state18))
    {
        ap_NS_fsm = ap_ST_fsm_state19;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state19))
    {
        ap_NS_fsm = ap_ST_fsm_state20;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state20))
    {
        ap_NS_fsm = ap_ST_fsm_state21;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state21))
    {
        ap_NS_fsm = ap_ST_fsm_state22;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state22))
    {
        ap_NS_fsm = ap_ST_fsm_state23;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state23))
    {
        ap_NS_fsm = ap_ST_fsm_state24;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state24))
    {
        ap_NS_fsm = ap_ST_fsm_state25;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state25))
    {
        ap_NS_fsm = ap_ST_fsm_state26;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state26))
    {
        ap_NS_fsm = ap_ST_fsm_state27;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state27))
    {
        ap_NS_fsm = ap_ST_fsm_state28;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state28))
    {
        ap_NS_fsm = ap_ST_fsm_state29;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state29))
    {
        ap_NS_fsm = ap_ST_fsm_state30;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state30))
    {
        ap_NS_fsm = ap_ST_fsm_state31;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state31))
    {
        ap_NS_fsm = ap_ST_fsm_state32;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state32))
    {
        ap_NS_fsm = ap_ST_fsm_state33;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state33))
    {
        ap_NS_fsm = ap_ST_fsm_state34;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state34))
    {
        ap_NS_fsm = ap_ST_fsm_state5;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state35))
    {
        ap_NS_fsm = ap_ST_fsm_state36;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state36))
    {
        ap_NS_fsm = ap_ST_fsm_state37;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state37))
    {
        ap_NS_fsm = ap_ST_fsm_state38;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state38))
    {
        ap_NS_fsm = ap_ST_fsm_state39;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state39))
    {
        ap_NS_fsm = ap_ST_fsm_state40;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state40))
    {
        ap_NS_fsm = ap_ST_fsm_state41;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state41))
    {
        ap_NS_fsm = ap_ST_fsm_state42;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state42))
    {
        ap_NS_fsm = ap_ST_fsm_state4;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state43))
    {
        ap_NS_fsm = ap_ST_fsm_state44;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state44))
    {
        ap_NS_fsm = ap_ST_fsm_state45;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state45))
    {
        ap_NS_fsm = ap_ST_fsm_state46;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state46))
    {
        ap_NS_fsm = ap_ST_fsm_state47;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state47))
    {
        ap_NS_fsm = ap_ST_fsm_state48;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state48))
    {
        ap_NS_fsm = ap_ST_fsm_state49;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state49))
    {
        ap_NS_fsm = ap_ST_fsm_state50;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state50))
    {
        ap_NS_fsm = ap_ST_fsm_state2;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state51))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state51.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln32_fu_260_p2.read()))) {
            ap_NS_fsm = ap_ST_fsm_state1;
        } else {
            ap_NS_fsm = ap_ST_fsm_state52;
        }
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state52))
    {
        ap_NS_fsm = ap_ST_fsm_state53;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state53))
    {
        ap_NS_fsm = ap_ST_fsm_state54;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state54))
    {
        ap_NS_fsm = ap_ST_fsm_state55;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state55))
    {
        ap_NS_fsm = ap_ST_fsm_state56;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state56))
    {
        ap_NS_fsm = ap_ST_fsm_state57;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state57))
    {
        ap_NS_fsm = ap_ST_fsm_state58;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state58))
    {
        ap_NS_fsm = ap_ST_fsm_state59;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state59))
    {
        ap_NS_fsm = ap_ST_fsm_state60;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state60))
    {
        ap_NS_fsm = ap_ST_fsm_state61;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state61))
    {
        ap_NS_fsm = ap_ST_fsm_state62;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state62))
    {
        ap_NS_fsm = ap_ST_fsm_state63;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state63))
    {
        ap_NS_fsm = ap_ST_fsm_state64;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state64))
    {
        ap_NS_fsm = ap_ST_fsm_state65;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state65))
    {
        ap_NS_fsm = ap_ST_fsm_state66;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state66))
    {
        ap_NS_fsm = ap_ST_fsm_state67;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state67))
    {
        ap_NS_fsm = ap_ST_fsm_state68;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state68))
    {
        ap_NS_fsm = ap_ST_fsm_state69;
    }
    else if (esl_seteq<1,69,69>(ap_CS_fsm.read(), ap_ST_fsm_state69))
    {
        ap_NS_fsm = ap_ST_fsm_state51;
    }
    else
    {
        ap_NS_fsm =  (sc_lv<69>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}
}

