# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/xl834/transformer/ECE6775FinalProjectTB/GEMM/zedboard_project/vivado-essentials/fifo_8x2048/fifo_8x2048.xci
# IP: The module: 'fifo_8x2048' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xl834/transformer/ECE6775FinalProjectTB/GEMM/zedboard_project/vivado-essentials/fifo_8x2048/fifo_8x2048.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8x2048'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/xl834/transformer/ECE6775FinalProjectTB/GEMM/zedboard_project/vivado-essentials/fifo_8x2048/fifo_8x2048_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8x2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/xl834/transformer/ECE6775FinalProjectTB/GEMM/zedboard_project/vivado-essentials/fifo_8x2048/fifo_8x2048.xci
# IP: The module: 'fifo_8x2048' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xl834/transformer/ECE6775FinalProjectTB/GEMM/zedboard_project/vivado-essentials/fifo_8x2048/fifo_8x2048.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8x2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/xl834/transformer/ECE6775FinalProjectTB/GEMM/zedboard_project/vivado-essentials/fifo_8x2048/fifo_8x2048_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8x2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
