-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dut is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    strm_in_a_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    strm_in_a_V_empty_n : IN STD_LOGIC;
    strm_in_a_V_read : OUT STD_LOGIC;
    strm_out_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    strm_out_V_full_n : IN STD_LOGIC;
    strm_out_V_write : OUT STD_LOGIC );
end;


architecture behav of dut is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "dut,hls_ip_2019_2_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.232000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=3,HLS_SYN_DSP=19,HLS_SYN_FF=3086,HLS_SYN_LUT=5172,HLS_VERSION=2019_2_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal strm_in_a_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln14_fu_117_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal strm_out_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal i_fu_123_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal i_1_fu_140_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal i_1_reg_162 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln23_fu_134_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal input1_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal input1_ce0 : STD_LOGIC;
    signal input1_we0 : STD_LOGIC;
    signal input1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal output_ce0 : STD_LOGIC;
    signal output_we0 : STD_LOGIC;
    signal output_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_softmax_128_s_fu_111_ap_start : STD_LOGIC;
    signal grp_softmax_128_s_fu_111_ap_done : STD_LOGIC;
    signal grp_softmax_128_s_fu_111_ap_idle : STD_LOGIC;
    signal grp_softmax_128_s_fu_111_ap_ready : STD_LOGIC;
    signal grp_softmax_128_s_fu_111_output_layer_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_softmax_128_s_fu_111_output_layer_ce0 : STD_LOGIC;
    signal grp_softmax_128_s_fu_111_probability_distribu_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_softmax_128_s_fu_111_probability_distribu_ce0 : STD_LOGIC;
    signal grp_softmax_128_s_fu_111_probability_distribu_we0 : STD_LOGIC;
    signal grp_softmax_128_s_fu_111_probability_distribu_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_0_reg_89 : STD_LOGIC_VECTOR (7 downto 0);
    signal i1_0_reg_100 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_softmax_128_s_fu_111_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state2_ignore_call0 : BOOLEAN;
    signal zext_ln16_fu_129_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln24_fu_146_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);

    component softmax_128_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        output_layer_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        output_layer_ce0 : OUT STD_LOGIC;
        output_layer_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        probability_distribu_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        probability_distribu_ce0 : OUT STD_LOGIC;
        probability_distribu_we0 : OUT STD_LOGIC;
        probability_distribu_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component softmax_128_s_eulbkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    input1_U : component softmax_128_s_eulbkb
    generic map (
        DataWidth => 32,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => input1_address0,
        ce0 => input1_ce0,
        we0 => input1_we0,
        d0 => strm_in_a_V_dout,
        q0 => input1_q0);

    output_U : component softmax_128_s_eulbkb
    generic map (
        DataWidth => 32,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => output_address0,
        ce0 => output_ce0,
        we0 => output_we0,
        d0 => grp_softmax_128_s_fu_111_probability_distribu_d0,
        q0 => output_q0);

    grp_softmax_128_s_fu_111 : component softmax_128_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_softmax_128_s_fu_111_ap_start,
        ap_done => grp_softmax_128_s_fu_111_ap_done,
        ap_idle => grp_softmax_128_s_fu_111_ap_idle,
        ap_ready => grp_softmax_128_s_fu_111_ap_ready,
        output_layer_address0 => grp_softmax_128_s_fu_111_output_layer_address0,
        output_layer_ce0 => grp_softmax_128_s_fu_111_output_layer_ce0,
        output_layer_q0 => input1_q0,
        probability_distribu_address0 => grp_softmax_128_s_fu_111_probability_distribu_address0,
        probability_distribu_ce0 => grp_softmax_128_s_fu_111_probability_distribu_ce0,
        probability_distribu_we0 => grp_softmax_128_s_fu_111_probability_distribu_we0,
        probability_distribu_d0 => grp_softmax_128_s_fu_111_probability_distribu_d0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_softmax_128_s_fu_111_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_softmax_128_s_fu_111_ap_start_reg <= ap_const_logic_0;
            else
                if ((not(((icmp_ln14_fu_117_p2 = ap_const_lv1_0) and (strm_in_a_V_empty_n = ap_const_logic_0))) and (icmp_ln14_fu_117_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_softmax_128_s_fu_111_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_softmax_128_s_fu_111_ap_ready = ap_const_logic_1)) then 
                    grp_softmax_128_s_fu_111_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i1_0_reg_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((strm_out_V_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                i1_0_reg_100 <= i_1_reg_162;
            elsif (((grp_softmax_128_s_fu_111_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i1_0_reg_100 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    i_0_reg_89_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((icmp_ln14_fu_117_p2 = ap_const_lv1_0) and (strm_in_a_V_empty_n = ap_const_logic_0))) and (icmp_ln14_fu_117_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_0_reg_89 <= i_fu_123_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_0_reg_89 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                i_1_reg_162 <= i_1_fu_140_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, strm_in_a_V_empty_n, strm_out_V_full_n, ap_CS_fsm_state2, icmp_ln14_fu_117_p2, ap_CS_fsm_state5, ap_CS_fsm_state4, icmp_ln23_fu_134_p2, grp_softmax_128_s_fu_111_ap_done, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((icmp_ln14_fu_117_p2 = ap_const_lv1_0) and (strm_in_a_V_empty_n = ap_const_logic_0))) and (icmp_ln14_fu_117_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif ((not(((icmp_ln14_fu_117_p2 = ap_const_lv1_0) and (strm_in_a_V_empty_n = ap_const_logic_0))) and (icmp_ln14_fu_117_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((grp_softmax_128_s_fu_111_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln23_fu_134_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                if (((strm_out_V_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_block_state2_assign_proc : process(strm_in_a_V_empty_n, icmp_ln14_fu_117_p2)
    begin
                ap_block_state2 <= ((icmp_ln14_fu_117_p2 = ap_const_lv1_0) and (strm_in_a_V_empty_n = ap_const_logic_0));
    end process;


    ap_block_state2_ignore_call0_assign_proc : process(strm_in_a_V_empty_n, icmp_ln14_fu_117_p2)
    begin
                ap_block_state2_ignore_call0 <= ((icmp_ln14_fu_117_p2 = ap_const_lv1_0) and (strm_in_a_V_empty_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state4, icmp_ln23_fu_134_p2)
    begin
        if (((icmp_ln23_fu_134_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4, icmp_ln23_fu_134_p2)
    begin
        if (((icmp_ln23_fu_134_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_softmax_128_s_fu_111_ap_start <= grp_softmax_128_s_fu_111_ap_start_reg;
    i_1_fu_140_p2 <= std_logic_vector(unsigned(i1_0_reg_100) + unsigned(ap_const_lv8_1));
    i_fu_123_p2 <= std_logic_vector(unsigned(i_0_reg_89) + unsigned(ap_const_lv8_1));
    icmp_ln14_fu_117_p2 <= "1" when (i_0_reg_89 = ap_const_lv8_80) else "0";
    icmp_ln23_fu_134_p2 <= "1" when (i1_0_reg_100 = ap_const_lv8_80) else "0";

    input1_address0_assign_proc : process(ap_CS_fsm_state2, icmp_ln14_fu_117_p2, grp_softmax_128_s_fu_111_output_layer_address0, ap_CS_fsm_state3, zext_ln16_fu_129_p1)
    begin
        if (((icmp_ln14_fu_117_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            input1_address0 <= zext_ln16_fu_129_p1(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input1_address0 <= grp_softmax_128_s_fu_111_output_layer_address0;
        else 
            input1_address0 <= "XXXXXXX";
        end if; 
    end process;


    input1_ce0_assign_proc : process(strm_in_a_V_empty_n, ap_CS_fsm_state2, icmp_ln14_fu_117_p2, grp_softmax_128_s_fu_111_output_layer_ce0, ap_CS_fsm_state3)
    begin
        if ((not(((icmp_ln14_fu_117_p2 = ap_const_lv1_0) and (strm_in_a_V_empty_n = ap_const_logic_0))) and (icmp_ln14_fu_117_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            input1_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input1_ce0 <= grp_softmax_128_s_fu_111_output_layer_ce0;
        else 
            input1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input1_we0_assign_proc : process(strm_in_a_V_empty_n, ap_CS_fsm_state2, icmp_ln14_fu_117_p2)
    begin
        if ((not(((icmp_ln14_fu_117_p2 = ap_const_lv1_0) and (strm_in_a_V_empty_n = ap_const_logic_0))) and (icmp_ln14_fu_117_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            input1_we0 <= ap_const_logic_1;
        else 
            input1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    output_address0_assign_proc : process(ap_CS_fsm_state4, grp_softmax_128_s_fu_111_probability_distribu_address0, ap_CS_fsm_state3, zext_ln24_fu_146_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            output_address0 <= zext_ln24_fu_146_p1(7 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            output_address0 <= grp_softmax_128_s_fu_111_probability_distribu_address0;
        else 
            output_address0 <= "XXXXXXX";
        end if; 
    end process;


    output_ce0_assign_proc : process(ap_CS_fsm_state4, grp_softmax_128_s_fu_111_probability_distribu_ce0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            output_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            output_ce0 <= grp_softmax_128_s_fu_111_probability_distribu_ce0;
        else 
            output_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    output_we0_assign_proc : process(grp_softmax_128_s_fu_111_probability_distribu_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            output_we0 <= grp_softmax_128_s_fu_111_probability_distribu_we0;
        else 
            output_we0 <= ap_const_logic_0;
        end if; 
    end process;


    strm_in_a_V_blk_n_assign_proc : process(strm_in_a_V_empty_n, ap_CS_fsm_state2, icmp_ln14_fu_117_p2)
    begin
        if (((icmp_ln14_fu_117_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            strm_in_a_V_blk_n <= strm_in_a_V_empty_n;
        else 
            strm_in_a_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    strm_in_a_V_read_assign_proc : process(strm_in_a_V_empty_n, ap_CS_fsm_state2, icmp_ln14_fu_117_p2)
    begin
        if ((not(((icmp_ln14_fu_117_p2 = ap_const_lv1_0) and (strm_in_a_V_empty_n = ap_const_logic_0))) and (icmp_ln14_fu_117_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            strm_in_a_V_read <= ap_const_logic_1;
        else 
            strm_in_a_V_read <= ap_const_logic_0;
        end if; 
    end process;


    strm_out_V_blk_n_assign_proc : process(strm_out_V_full_n, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            strm_out_V_blk_n <= strm_out_V_full_n;
        else 
            strm_out_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    strm_out_V_din <= output_q0;

    strm_out_V_write_assign_proc : process(strm_out_V_full_n, ap_CS_fsm_state5)
    begin
        if (((strm_out_V_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            strm_out_V_write <= ap_const_logic_1;
        else 
            strm_out_V_write <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln16_fu_129_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_0_reg_89),64));
    zext_ln24_fu_146_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i1_0_reg_100),64));
end behav;
